name: update readme
on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:
   

jobs:

  update_readme:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: generate report
      run: |
        curl -vL https://eulermaker.compass-ci.openeuler.openatom.cn/api/data-api/search
        python3 check_ebs.py
        ls -alh
    
    - name: Commit report
      run: |
        git config --global user.name 'oervci'
        git config --global user.email 'rvci@isrc.iscas.ac.cn'
        git commit -am "update README.md"
        git push