name: update readme
on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:
   

jobs:

  update_readme:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: generate report
      run: |
        python3 check_ebs.py

    - name: Commit report
      uses: test-room-7/action-update-file@v1
      with:
        file-path: README.md
        commit-msg: Update README.md
        github-token: ${{ secrets.ACFAILEDDISPLAY_GITHUB_TOKEN }}