name: update readme
on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:
   

jobs:

  update_readme:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: generate report
      run: |
        python3 check_ebs.py

    - name: Commit report
      run: |
        git add *
        git config --global user.name 'oervci'
        git config --global user.email 'rvci@isrc.iscas.ac.cn'
        git commit -m "update README.md"
        git push